'''
services:
  # A name for your service
  - name: clausespy
    # The type of service to create
    type: web
    # The runtime environment for your app
    env: python
    # The command to build your app
    buildCommand: "pip install -r requirements.txt"
    # The command to start your app
    startCommand: "gunicorn app:app"
'''
